### ISSUE TITLE
Support for Integers

### ISSUE THREAD

**Issue by martin-kieliszek** [manu-de-verdun/sql-json-generator#7]
Would it be possible to enable support for integers such that where comparisons don't catch an exception like below?

Request:
```
{
	    		"$field" : "dt",
	    		"$gte" : 20180226
}
```
Request maps to an sql query that has the following where clause
```
"dt" >= '20180226'
```
Error thrown from target DB
```
'>=' cannot be applied to integer, varchar(8)"
```

Seeing as though the request is issued as an int (and not a string) is it possible for the sql generator to preserve that int as opposed to wrapping it within two apostrophes?

If a flag could be set for such an event, that would be great

**Comment by martin-kieliszek** [comment]
Perhaps @manu-de-verdun @emmanuelpautet 

```
    var escaping = function (data) {
        
        if (typeof data === 'string' && options.escaped) {
            return sqlString.escape(data);
        }
        else if (typeof data === 'string'){
            return "'" + data + "'";
        }
        else {
            return data;
        }
    }
```

Note: although you don't support PrestoDB - I am using PrestoDB. The above is a modification that would help with regards to my issue and potentially a number of others, without breaking your existing implementation

**Comment by manu-de-verdun** [comment]
Hi, @martin-kieliszek 

Let me understand: using PrestoDB , numbers (int, or other number types) can not be wrapped in apostrophes? 

I'm not familiar with PrestoDB

what is the correct PrestoDB SQL syntax, are there other specificities ?

NOT CORRECT
`SELECT id FROM table where id >= '100';`

CORRECT
`SELECT id FROM table where id >= 100;`

**Comment by martin-kieliszek** [comment]
@manu-de-verdun 

1. Correct, numbers cannot be wrapped in apostrophes!

Other specifics:

2. After sql-json-generator completes building, the sql has "\`" characters within the query. I am replacing all instances of "\`" with "
(I can do this on my end, perhaps not necessary for you to need to modify your library)
```
sql = sql.replace(/`/g, '"')
```
3. PrestoDB syntax doesn't allow limits in the following syntax
```
LIMIT 0,20
```
Instead it allows
```
LIMIT 20
```
(I am able to avoid using a limit key during generation, and instead append my limit as a string to the completed query)

The only thing I have not been able to "work around" without needing to modify your awesome library, is this integer fix listed in previous comment.

Thanks for helping!

**Comment by manu-de-verdun** [comment]
@martin-kieliszek 

I did not merge the update you send because it is not exactly the way the module works: Initialy created to generate mySQL statements, I have made enhancements to allow the generation of other SQL (pgSQL).

I added a new SQL suport for prestoDB, and implemented the 2 issues: numbers in query and limit (without offset)

to use the presto SQL syntax, you have to  declare like this:
`var sqlGenerator = new SQLGenerator({ prestoDB: true });`

You can test the query building engine using dev/app.js, standalone app

you can run an npm test to run all tests.

Can you test it and give me a feedback ?

**Comment by martin-kieliszek** [comment]
Have tested and am very happy! Appreciate your communication and effort

Thanks for releasing this change @manu-de-verdun 

Happy for you to close this issue

**Comment by manu-de-verdun** [comment]
Solved

**Comment by martin-kieliszek** [comment]
@manu-de-verdun My team and I have very happily been using your library for a couple of months now - you are to be commended!

One interesting querk that we have noticed (understandably in hindsight) is that when we pass in `prestoDB:true` everything works beautifully  until an integer of 0 is passed in. This ofcourse is because the library never previously supported integer parameters. 

```
{
  "$field" : "id",
  "$gt" : 0
}
```


Conditions on line 133 through to 176 will be skipped when using the prestoDB integer comparisons for 0. For the above example, this line will result in a false:

``` 
// Line 133
           if (conditions["$gt"]) { // when the condition value is equal to integer 0, this will assert false. perhaps an extra condition to check it is not null when using prestoDB may be required instead?
                return conditionBuilder(conditions['$field'], currentTable, '>', conditions["$gt"]);
            }

// results in an and statement like so:
// .... WHERE  AND ....
```


Can you confirm whether the statements that are made between 133 and 176 are simply trying to check if the value is not null? If so I can make this modification as a PR if you like? I am surprised this issue didn't surface quicker in all of our use-cases but here we are! (Apparently my team only cared for integers greater than 0 in the past 2 months)!

In any case, would like to get your view and opinion. 

Raw is working as normal, but would DEFINITELY like to use your existing aggregation options if possible, when fixed

Kindest regards,
Marty
